version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 9678:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-admin}
      - MONGO_DATABASE=${MONGO_DATABASE:-stri}
      - PRODUCTION=${PRODUCTION:-false}
    volumes:
      - ./db:/data/db
    command: --smallfiles

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./backend:/usr/app/
      - ./backend/node_modules:/usr/app/node_modules
    ports:
      - 8200:3000
    depends_on:
      - mongo
    environment:
      - TZ=UTC
      - PRODUCTION=${PRODUCTION:-false}
      - MONGO_USER=${MONGO_USER:-admin}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-admin}
      - MONGO_DATABASE=${MONGO_DATABASE:-stri}
      - APP_DOMAIN=${APP_DOMAIN:-asher.sciling.com}
      - APP_DOMAIN_DEV=${APP_DOMAIN_DEV:-localhost}
      - NODE_ENV=${PRODUCTION:-true}
      - S
  angular:
    image: nginx
    links:
      - "backend:node_api"
    volumes:
      - ./frontend/dist/stripe-test:/var/www/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8202:80"
    restart: always
    environment:
      - TZ=UTC
      - PRODUCTION=${PRODUCTION:-false}
      - APP_DOMAIN=${APP_DOMAIN:-asher.sciling.com}
      - APP_DOMAIN_DEV=${APP_DOMAIN_DEV:-localhost}
    depends_on:
      - backend
